{% set name = "pygeohydro" %}
{% set version = "0.13.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeohydro-{{ version }}.tar.gz
  sha256: 96e52847e8751c9f81c9808358fd803720bb4fce4811200c710dcb9ef87468ec

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - async_retriever >=0.3.4
    - cytoolz
    - defusedxml
    - exceptiongroup
    - folium
    - geopandas >=0.8
    - h5netcdf
    - lxml
    - numpy >=1.17
    - pandas >=1.0
    - proplot
    - pygeoogc >=0.13.3
    - pygeoutils >=0.13.2
    - pynhd >=0.13.3
    - python >=3.8
    - rasterio
    - scipy
    - shapely >=1.7
    - xarray >=2022.03.0

test:
  imports:
    - pygeohydro
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/pygeohydro
  summary: Access geospatial hydrology web services through Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
