{% set name = "pygeohydro" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygeohydro-{{ version }}.tar.gz
  sha256: cc3644acc9651796a24ac8b1a8e8c2ffc789852dc4061eb51812f5a8c3d0cdc5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.12
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - async-retriever <0.19,>=0.18
    - cytoolz
    - defusedxml
    - folium
    - geopandas-base >=1
    - h5netcdf
    - hydrosignatures <0.19,>=0.18
    - lxml
    - matplotlib-base >=3.5
    - numpy >=1.21
    - pandas >=1.0
    - pygeoogc <0.19,>=0.18
    - pygeoutils <0.19,>=0.18
    - pynhd <0.19,>=0.18
    - pyproj >=3.0.1
    - rasterio >=1.2
    - rioxarray >=0.11
    - scipy
    - shapely >=2
    - ujson
    - xarray >=2023.01.0

test:
  imports:
    - pygeohydro
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hyriver/pygeohydro
  summary: Access geospatial web services that offer hydrological data
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
